import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserratFont = Montserrat({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["cyrillic", "latin"],
});
export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${montserratFont.style} antialiased`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
